server:
  port: 8081
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-30002792.okta.com/oauth2/default
          jwk-set-uri: https://dev-30002792.okta.com/oauth2/default/v1/keys